version: '3.7'

secrets:
  access_key:
    file: ./secrets/rgw_access_key
  secret_key:
    file: ./secrets/rgw_secret_key

services:
  minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    container_name: minio
    volumes:
      - data:/data
    ports:
      - '9000:9000'
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/access_key
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/secret_key
      # MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      # MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data
    secrets:
      - access_key
      - secret_key
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  # console:
  #   image: minio/console:v0.7.4
  #   container_name: minio-console
  #   command: server
  #   secrets:
  #     - access_key
  #     - secret_key
  #   ports:
  #     - '9090:9090'
  #   environment:
  #     TZ: ${TZ}
  #     CONSOLE_MINIO_SERVER: http://minio:9000
  #     # Salt to encrypt JWT payload
  #     CONSOLE_PBKDF_PASSPHRASE: SECRET
  #     # Required to encrypt JWT payload
  #     CONSOLE_PBKDF_SALT: SECRET

volumes:
  data:
